name: flutter_dio_tutorial
description: Dio package tutorial.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  injectable: ^1.4.1
  json_annotation: ^4.0.1
  logger: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter:
  uses-material-design: true
